const { createStore, kindText, statusText } = window.LostFoundStore;
const store = createStore();
const root = document.querySelector('#app');
const locations = ['教学楼', '图书馆', '食堂', '宿舍区'];
let route = { page: 'home' };
const esc = (v) => String(v).replace(/[&<>'"]/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[c]));
function go(page, data) { route = Object.assign({ page }, data || {}); render(); window.scrollTo(0, 0); }
function nav() { return '<nav class="bottom-nav"><button class="' + (route.page === 'home' ? 'active' : '') + '" data-nav="home">⌂<span>首页</span></button><button class="' + (route.page === 'publish' ? 'active' : '') + '" data-nav="publish">＋<span>发布</span></button><button class="' + (route.page === 'mine' ? 'active' : '') + '" data-nav="mine">♙<span>我的发布</span></button></nav>'; }
function card(p) { return '<button class="post-card" data-open="' + p.id + '"><span class="kind-icon ' + p.kind + '">' + (p.kind === 'lost' ? '⌕' : '✓') + '</span><span class="post-main"><strong>' + esc(p.name) + '</strong><small>' + esc(p.location) + ' · ' + esc(p.place) + '</small><small>' + esc(p.happenedAt) + '</small></span><span class="post-side"><i class="pill ' + p.status + '">' + statusText(p) + '</i><em>' + kindText(p.kind) + '</em></span></button>'; }
function home() { const posts = store.list({ kind: route.kind || '' }); const s = store.stats(); return '<section class="screen"><header class="hero"><p class="eyebrow">校园失物招领</p><h1>让每一件遗失的物品都能回家</h1><button class="search-bar" data-nav="search">⌕　搜索物品名称、地点或关键词 <b>搜索</b></button></header><main><div class="stats"><span><b>' + s.total + '</b>全部信息</span><span><b>' + s.open + '</b>待解决</span><span><b>' + s.resolved + '</b>已解决</span></div><div class="segmented"><button data-kind="" class="' + (!route.kind ? 'selected' : '') + '">全部 ' + store.list().length + '</button><button data-kind="lost" class="' + (route.kind === 'lost' ? 'selected' : '') + '">寻物</button><button data-kind="found" class="' + (route.kind === 'found' ? 'selected' : '') + '">招领</button></div><p class="notice">✓ 发布者可以把信息标记为已找到或已归还</p><div class="section-head"><h2>全部信息</h2><span>待解决优先展示</span></div><div class="post-list">' + (posts.map(card).join('') || '<p class="empty">暂无符合条件的信息</p>') + '</div></main>' + nav() + '</section>'; }
function search() { const posts = store.list({ keyword: route.keyword || '', kind: route.kind || '', location: route.location || '' }); const placeButtons = locations.map((x) => '<button data-location="' + x + '" class="' + (route.location === x ? 'outline-on' : '') + '">' + x + '</button>').join(''); return '<section class="screen subpage"><header class="sub-header"><button data-nav="home">‹</button><form id="search-form"><input name="keyword" value="' + esc(route.keyword || '') + '" placeholder="搜索物品名称、地点或关键词"><button>搜索</button></form></header><main><div class="filter-row"><label>类型</label><button data-search-kind="" class="' + (!route.kind ? 'outline-on' : '') + '">全部</button><button data-search-kind="lost" class="' + (route.kind === 'lost' ? 'outline-on' : '') + '">寻物</button><button data-search-kind="found" class="' + (route.kind === 'found' ? 'outline-on' : '') + '">招领</button></div><div class="filter-row"><label>地点</label><button data-location="" class="' + (!route.location ? 'outline-on' : '') + '">全部</button>' + placeButtons + '</div><p class="result-count">找到 ' + posts.length + ' 条相关信息</p><div class="post-list">' + (posts.map(card).join('') || '<p class="empty">没有找到匹配信息，请更换关键词或筛选条件。</p>') + '</div></main></section>'; }
function publish() { const options = locations.map((x) => '<option>' + x + '</option>').join(''); return '<section class="screen subpage"><header class="sub-header"><button data-nav="home">‹</button><h1>发布信息</h1><span></span></header><main><form id="publish-form" class="form-card"><div class="type-switch"><button type="button" data-form-kind="lost" class="selected">寻物</button><button type="button" data-form-kind="found">招领</button></div><p id="form-hint">发布寻物信息：说明遗失的物品、时间和地点</p><label>物品名称*<input name="name" placeholder="例如：校园卡、AirPods" required></label><label>物品类别*<select name="category"><option>证件卡片</option><option>数码产品</option><option>生活用品</option><option>其他</option></select></label><label>地点*<select name="location">' + options + '</select></label><label>具体位置*<input name="place" placeholder="例如：三楼自习区靠窗长桌" required></label><label>时间*<input name="happenedAt" type="datetime-local" required></label><label>物品描述*<textarea name="description" placeholder="颜色、特征、是否有标记等" required></textarea></label><label>联系方式*<input name="contact" placeholder="11 位手机号" required></label><input name="kind" value="lost" type="hidden"><button class="primary" type="submit">发布信息</button></form></main>' + nav() + '</section>'; }
function detail() { const p = store.get(route.id); if (!p) return home(); const manage = p.publisher === '林金晶' && p.status === 'open' ? '<button class="secondary" id="resolve-btn">标记为' + (p.kind === 'lost' ? '已找到' : '已归还') + '</button>' : ''; return '<section class="screen subpage"><header class="sub-header"><button data-nav="' + (route.from || 'home') + '">‹</button><h1>信息详情</h1><span>•••</span></header><main class="detail"><article class="detail-card"><div class="detail-title"><span class="kind-icon ' + p.kind + '">' + (p.kind === 'lost' ? '⌕' : '✓') + '</span><div><h2>' + esc(p.name) + ' <i class="pill ' + p.status + '">' + statusText(p) + '</i></h2><p>' + kindText(p.kind) + ' · ' + esc(p.category) + '</p></div></div><div class="meta-grid"><span><small>发生时间</small>' + esc(p.happenedAt) + '</span><span><small>信息编号</small>' + p.id + '</span></div></article><article class="detail-card"><h3>⌖ ' + (p.kind === 'lost' ? '遗失地点' : '拾取地点') + '</h3><p>' + esc(p.location) + ' · ' + esc(p.place) + '</p></article><article class="detail-card"><h3>▤ 物品描述</h3><p>' + esc(p.description) + '</p></article><article class="detail-card"><h3>♙ 发布者</h3><p>' + esc(p.publisher) + ' · ' + kindText(p.kind) + '信息发布者</p><p class="contact" id="contact-value">联系方式将于点击后显示</p></article></main><footer class="action-bar"><button id="contact-btn">联系发布者</button>' + manage + '</footer></section>'; }
function mine() { const posts = store.list().filter((p) => p.publisher === '林金晶'); return '<section class="screen subpage"><header class="sub-header"><button data-nav="home">‹</button><h1>我的发布</h1><span>⚙</span></header><main><section class="profile"><strong>林金晶</strong><span>102401505 · 校园失物招领</span><div><b>' + posts.length + '<small>发布总数</small></b><b>' + posts.filter((p) => p.status === 'open').length + '<small>未解决</small></b><b>' + posts.filter((p) => p.status === 'resolved').length + '<small>已解决</small></b></div></section><div class="section-head"><h2>我的记录</h2><span>可在详情更新状态</span></div><div class="post-list">' + (posts.map(card).join('') || '<p class="empty">还没有发布记录</p>') + '</div></main>' + nav() + '</section>'; }
function render() { root.innerHTML = route.page === 'publish' ? publish() : route.page === 'search' ? search() : route.page === 'detail' ? detail() : route.page === 'mine' ? mine() : home(); bind(); }
function bind() {
  document.querySelectorAll('[data-nav]').forEach((x) => x.addEventListener('click', () => go(x.dataset.nav)));
  document.querySelectorAll('[data-open]').forEach((x) => x.addEventListener('click', () => go('detail', { id: x.dataset.open, from: route.page })));
  document.querySelectorAll('[data-kind]').forEach((x) => x.addEventListener('click', () => { route.kind = x.dataset.kind; render(); }));
  document.querySelectorAll('[data-search-kind]').forEach((x) => x.addEventListener('click', () => { route.kind = x.dataset.searchKind; render(); }));
  document.querySelectorAll('[data-location]').forEach((x) => x.addEventListener('click', () => { route.location = x.dataset.location; render(); }));
  const sf = document.querySelector('#search-form'); if (sf) sf.addEventListener('submit', (e) => { e.preventDefault(); route.keyword = new FormData(sf).get('keyword'); render(); });
  document.querySelectorAll('[data-form-kind]').forEach((x) => x.addEventListener('click', () => { document.querySelectorAll('[data-form-kind]').forEach((b) => b.classList.toggle('selected', b === x)); document.querySelector('[name="kind"]').value = x.dataset.formKind; document.querySelector('#form-hint').textContent = x.dataset.formKind === 'lost' ? '发布寻物信息：说明遗失的物品、时间和地点' : '发布招领信息：说明拾取的物品、时间和地点'; }));
  const form = document.querySelector('#publish-form'); if (form) form.addEventListener('submit', (e) => { e.preventDefault(); const data = Object.fromEntries(new FormData(form)); data.happenedAt = data.happenedAt.replace('T', ' '); try { const p = store.add(data); go('detail', { id: p.id, from: 'mine' }); } catch (err) { alert(err.message); } });
  const contact = document.querySelector('#contact-btn'); if (contact) contact.addEventListener('click', async () => { const p = store.get(route.id); if (!contact.dataset.ready) { document.querySelector('#contact-value').textContent = '联系方式：' + p.contact; contact.textContent = '一键复制联系方式'; contact.dataset.ready = 'true'; return; } try { if (navigator.clipboard && navigator.clipboard.writeText) await navigator.clipboard.writeText(p.contact); else { const t = document.createElement('textarea'); t.value = p.contact; document.body.append(t); t.select(); document.execCommand('copy'); t.remove(); } contact.textContent = '已复制联系方式'; } catch (e) { contact.textContent = '复制失败，请手动复制'; } });
  const resolve = document.querySelector('#resolve-btn'); if (resolve) resolve.addEventListener('click', () => { store.resolve(route.id); render(); });
}
render();
